services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Wortfreunde\WortfreundeConnector\:
    resource: '../Classes/*'

  Wortfreunde\WortfreundeConnector\Service\MarkdownConverterService:
    public: true

  Wortfreunde\WortfreundeConnector\Service\WebhookProcessorService:
    public: true

  Wortfreunde\WortfreundeConnector\Middleware\WebhookMiddleware:
    public: true

  Wortfreunde\WortfreundeConnector\Controller\WebhookLogController:
    public: true
